FROM node:14 AS Production

ENV  REACT_APP_API="http://localhost:5000" REACT_APP_EXAMPLE_JWT="Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGViYzI0MDRhNmVkNDU2NzUwOTk4YjEiLCJ1c2VybmFtZSI6ImpvaG4iLCJleHAiOjE2MjY5NTgwMzEuMjA3LCJpYXQiOjE2MjYzNTMyMzF9.3t_YzKPq4jk6UuIkzTgFaLoXD0Pq5ktmRFp7xg6dFYU" REACT_APP_SOCKET_PORT="http://localhost:5000"

WORKDIR /usr/src/client

COPY package.json . 
COPY package-lock.json .

RUN npm install

COPY . . 

RUN npm run build

CMD ["sh", "-c","npm run start"]