export const  Users = [
    {
        id:1,
        profilePicture:"person/1.jpg",
        username:"陳慕真",
    },
    {
        id:2,
        profilePicture:"person/2.jpg",
        username:"林士淵",
    },
    {
        id:3,
        profilePicture:"person/3.jpg",
        username:"梁呈瑋",
    },
    {
        id:4,
        profilePicture:"person/4.jpg",
        username:"劉承揚",
    },
    {
        id:5,
        profilePicture:"person/5.jpg",
        username:"蕭心玫",
    },
    {
        id:7,
        profilePicture:"person/7.jpg",
        username:"陳亮均",
    },
    {
        id:8,
        profilePicture:"person/8.jpg",
        username:"楊均富",
    },
    {
        id:9,
        profilePicture:"person/9.jpg",
        username:"李培安",
    },
    {
        id:10,
        profilePicture:"person/10.jpg",
        username:"游旻昌",
    },
];

export const Posts = [
    {
        id:1,
        desc:"愛上霸道總裁昌哥",
        photo:"post/1.webp",
        date:"5 mins ago",
        userId:1,
        like:32,
        comment:9,
    },
    {
        id:2,
        desc:"第一次發文大家不要生氣",
        photo:"post/2.jpg",
        date:"15 mins ago",
        userId:2,
        like:2,
        comment:1,
    },
    {
        id:3,
        desc:"昌哥好帥",
        photo:"post/3.jpg",
        date:"20 mins ago",
        userId:3,
        like:100,
        comment:15,
    },
    {
        id:4,
        desc:"媽的圖文不符",
        photo:"post/4.jpg",
        date:"5 mins ago",
        userId:4,
        like:10,
        comment:5,
    },
    {
        id:5,
        desc:"昌哥什麼時候要去玩",
        photo:"post/5.jpg",
        date:"5 mins ago",
        userId:5,
        like:30,
        comment:8,
    },
];

export const  Countries =  [  
    {"code": "HK", "en": "Hong Kong", "cn": "香港"},  
    {"code": "TW", "en": "Taiwan", "cn": "台灣"},  
    {"code": "MO", "en": "Macao", "cn": "澳門"},  
    {"code": "US", "en": "United States of America (USA)", "cn": "美國"},  
    {"code": "AR", "en": "Argentina", "cn": "阿根廷"},  
    {"code": "AD", "en": "Andorra", "cn": "安道爾"},  
    {"code": "AE", "en": "United Arab Emirates", "cn": "阿聯酋"},  
    {"code": "AF", "en": "Afghanistan", "cn": "阿富汗"},  
    {"code": "AG", "en": "Antigua & Barbuda", "cn": "安地卡及巴布達"},  
    {"code": "AI", "en": "Anguilla", "cn": "安圭拉"},  
    {"code": "AL", "en": "Albania", "cn": "阿爾巴尼亞"},  
    {"code": "AM", "en": "Armenia", "cn": "亞美尼亞"},  
    {"code": "AO", "en": "Angola", "cn": "安哥拉"},  
    {"code": "AQ", "en": "Antarctica", "cn": "南極洲"},  
    {"code": "AS", "en": "American Samoa", "cn": "美屬薩摩亞"},  
    {"code": "AT", "en": "Austria", "cn": "奧地利"},  
    {"code": "AU", "en": "Australia", "cn": "澳大利亞"},  
    {"code": "AW", "en": "Aruba", "cn": "阿魯巴"},  
    {"code": "AX", "en": "Aland Island", "cn": "奧蘭群島"},  
    {"code": "AZ", "en": "Azerbaijan", "cn": "亞塞拜然"},  
    {"code": "BA", "en": "Bosnia & Herzegovina", "cn": "波黑"},  
    {"code": "BB", "en": "Barbados", "cn": "巴貝多"},  
    {"code": "BD", "en": "Bangladesh", "cn": "孟加拉"},  
    {"code": "BE", "en": "Belgium", "cn": "比利時"},  
    {"code": "BF", "en": "Burkina", "cn": "布吉納法索"},  
    {"code": "BG", "en": "Bulgaria", "cn": "保加利亞"},  
    {"code": "BH", "en": "Bahrain", "cn": "巴林"},  
    {"code": "BI", "en": "Burundi", "cn": "蒲隆地"},  
    {"code": "BJ", "en": "Benin", "cn": "貝南"},  
    {"code": "BL", "en": "Saint Barthélemy", "cn": "聖巴泰勒米島"},  
    {"code": "BM", "en": "Bermuda", "cn": "百慕大"},  
    {"code": "BN", "en": "Brunei", "cn": "汶萊"},  
    {"code": "BO", "en": "Bolivia", "cn": "玻利維亞"},  
    {"code": "BQ", "en": "Caribbean Netherlands", "cn": "荷蘭加勒比區"},  
    {"code": "BR", "en": "Brazil", "cn": "巴西"},  
    {"code": "BS", "en": "The Bahamas", "cn": "巴哈馬"},  
    {"code": "BT", "en": "Bhutan", "cn": "不丹"},  
    {"code": "BV", "en": "Bouvet Island", "cn": "布韋島"},  
    {"code": "BW", "en": "Botswana", "cn": "波札那"},  
    {"code": "BY", "en": "Belarus", "cn": "白俄羅斯"},  
    {"code": "BZ", "en": "Belize", "cn": "貝里斯"},  
    {"code": "CA", "en": "Canada", "cn": "加拿大"},  
    {"code": "CC", "en": "Cocos (Keeling) Islands", "cn": "科科斯群島"},  
    {"code": "CD", "en": "Democratic Republic of the Congo", "cn": "剛果（金）"},  
    {"code": "CF", "en": "Central African Republic", "cn": "中非"},  
    {"code": "CG", "en": "Republic of the Congo", "cn": "剛果（布）"},  
    {"code": "CH", "en": "Switzerland", "cn": "瑞士"},  
    {"code": "CI", "en": "Cote d'Ivoire", "cn": "象牙海岸"},  
    {"code": "CK", "en": "Cook Islands", "cn": "庫克群島"},  
    {"code": "CL", "en": "Chile", "cn": "智利"},  
    {"code": "CM", "en": "Cameroon", "cn": "喀麥隆"},  
    {"code": "CN", "en": "China", "cn": "中國"},  
    {"code": "CO", "en": "Colombia", "cn": "哥倫比亞"},  
    {"code": "CR", "en": "Costa Rica", "cn": "哥斯大黎加"},  
    {"code": "CU", "en": "Cuba", "cn": "古巴"},  
    {"code": "CV", "en": "Cape Verde", "cn": "維德角"},  
    {"code": "CW", "en": "Curacao", "cn": "庫拉索"},  
    {"code": "CX", "en": "Christmas Island", "cn": "聖誕島"},  
    {"code": "CY", "en": "Cyprus", "cn": "塞普勒斯"},  
    {"code": "CZ", "en": "Czech Republic", "cn": "捷克"},  
    {"code": "DE", "en": "Germany", "cn": "德國"},  
    {"code": "DJ", "en": "Djibouti", "cn": "吉布提"},  
    {"code": "DK", "en": "Denmark", "cn": "丹麥"},  
    {"code": "DM", "en": "Dominica", "cn": "多米尼克"},  
    {"code": "DO", "en": "Dominican Republic", "cn": "多明尼加"},  
    {"code": "DZ", "en": "Algeria", "cn": "阿爾及利亞"},  
    {"code": "EC", "en": "Ecuador", "cn": "厄瓜多"},  
    {"code": "EE", "en": "Estonia", "cn": "愛沙尼亞"},  
    {"code": "EG", "en": "Egypt", "cn": "埃及"},  
    {"code": "EH", "en": "Western Sahara", "cn": "西撒哈拉"},  
    {"code": "ER", "en": "Eritrea", "cn": "厄利垂亞"},  
    {"code": "ES", "en": "Spain", "cn": "西班牙"},  
    {"code": "ET", "en": "Ethiopia", "cn": "衣索比亞"},  
    {"code": "FI", "en": "Finland", "cn": "芬蘭"},  
    {"code": "FJ", "en": "Fiji", "cn": "斐濟群島"},
    {"code": "FK", "en": "Falkland Islands", "cn": "馬爾維納斯群島（福克蘭）" },  
    {"code": "FM", "en": "Federated States of Micronesia", "cn": "密克羅尼西亞聯邦"},  
    {"code": "FO", "en": "Faroe Islands", "cn": "法羅群島"},  
    {"code": "FR", "en": "France", "cn": "法國 法國"},  
    {"code": "GA", "en": "Gabon", "cn": "加彭"},  
    {"code": "GB", "en": "Great Britain (United Kingdom; England)", "cn": "英國"},  
    {"code": "GD", "en": "Grenada", "cn": "格瑞那達"},  
    {"code": "GE", "en": "Georgia", "cn": "喬治亞"},  
    {"code": "GF", "en": "French Guiana", "cn": "法屬蓋亞那"},  
    {"code": "GG", "en": "Guernsey", "cn": "根西島"},  
    {"code": "GH", "en": "Ghana", "cn": "迦納"},  
    {"code": "GI", "en": "Gibraltar", "cn": "直布羅陀"},  
    {"code": "GL", "en": "Greenland", "cn": "格陵蘭"},  
    {"code": "GM", "en": "Gambia", "cn": "甘比亞"},  
    {"code": "GN", "en": "Guinea", "cn": "幾內亞"},  
    {"code": "GP", "en": "Guadeloupe", "cn": "瓜德羅普"},  
    {"code": "GQ", "en": "Equatorial Guinea", "cn": "赤道幾內亞"},  
    {"code": "GR", "en": "Greece", "cn": "希臘"},  
    {"code": "GS", "en": "South Georgia and the South Sandwich Islands", "cn": "南喬治亞島和南桑威奇群島"},  
    {"code": "GT", "en": "Guatemala", "cn": "瓜地馬拉"},  
    {"code": "GU", "en": "Guam", "cn": "關島"},  
    {"code": "GW", "en": "Guinea-Bissau", "cn": "幾內亞比索"},  
    {"code": "GY", "en": "Guyana", "cn": "蓋亞那"},  
    {"code": "HM", "en": "Heard Island and McDonald Islands", "cn": "赫德島和麥克唐納群島"},  
    {"code": "HN", "en": "Honduras", "cn": "宏都拉斯"},  
    {"code": "HR", "en": "Croatia", "cn": "克羅埃西亞"},  
    {"code": "HT", "en": "Haiti", "cn": "海地"},  
    {"code": "HU", "en": "Hungary", "cn": "匈牙利"},  
    {"code": "ID", "en": "Indonesia", "cn": "印尼"},  
    {"code": "IE", "en": "Ireland", "cn": "愛爾蘭"},  
    {"code": "IL", "en": "Israel", "cn": "以色列"},  
    {"code": "IM", "en": "Isle of Man", "cn": "馬恩島"},  
    {"code": "IN", "en": "India", "cn": "印度"},  
    {"code": "IO", "en": "British Indian Ocean Territory", "cn": "英屬印度洋領地"},  
    {"code": "IQ", "en": "Iraq", "cn": "伊拉克"},  
    {"code": "IR", "en": "Iran", "cn": "伊朗"},  
    {"code": "IS", "en": "Iceland", "cn": "冰島"},  
    {"code": "IT", "en": "Italy", "cn": "義大利"},  
    {"code": "JE", "en": "Jersey", "cn": "澤西島"},  
    {"code": "JM", "en": "Jamaica", "cn": "牙買加"},  
    {"code": "JO", "en": "Jordan", "cn": "約旦"},  
    {"code": "JP", "en": "Japan", "cn": "日本"},  
    {"code": "KE", "en": "Kenya", "cn": "肯亞"},  
    {"code": "KG", "en": "Kyrgyzstan", "cn": "吉爾吉斯斯坦"},  
    {"code": "KH", "en": "Cambodia", "cn": "柬埔寨"},  
    {"code": "KI", "en": "Kiribati", "cn": "吉里巴斯"},  
    {"code": "KM", "en": "The Comoros", "cn": "葛摩"},  
    {"code": "KN", "en": "St. Kitts & Nevis", "cn": "聖克里斯多福及尼維斯"},  
    {"code": "KP", "en": "North Korea", "cn": "朝鮮"},  
    {"code": "KR", "en": "South Korea", "cn": "韓國"},  
    {"code": "KW", "en": "Kuwait", "cn": "科威特"},  
    {"code": "KY", "en": "Cayman Islands", "cn": "開曼群島"},  
    {"code": "KZ", "en": "Kazakhstan", "cn": "哈薩克"},  
    {"code": "LA", "en": "Laos", "cn": "寮國"},  
    {"code": "LB", "en": "Lebanon", "cn": "黎巴嫩"},  
    {"code": "LC", "en": "St. Lucia", "cn": "聖露西亞"},  
    {"code": "LI", "en": "Liechtenstein", "cn": "列支敦斯登"},  
    {"code": "LK", "en": "Sri Lanka", "cn": "斯里蘭卡"},  
    {"code": "LR", "en": "Liberia", "cn": "賴比瑞亞"},  
    {"code": "LS", "en": "Lesotho", "cn": "賴索托"},  
    {"code": "LT", "en": "Lithuania", "cn": "立陶宛"},  
    {"code": "LU", "en": "Luxembourg", "cn": "盧森堡"},  
    {"code": "LV", "en": "Latvia", "cn": "拉脫維亞"},  
    {"code": "LY", "en": "Libya", "cn": "利比亞"},  
    {"code": "MA", "en": "Morocco", "cn": "摩洛哥"},  
    {"code": "MC", "en": "Monaco", "cn": "摩納哥"},  
    {"code": "MD", "en": "Moldova", "cn": "摩爾多瓦"},  
    {"code": "ME", "en": "Montenegro", "cn": "黑山"},  
    {"code": "MF", "en": "Saint Martin (France)", "cn": "法屬聖馬丁"},  
    {"code": "MG", "en": "Madagascar", "cn": "馬達加斯加"},  
    {"code": "MH", "en": "Marshall islands", "cn": "馬紹爾群島"},  
    {"code": "MK", "en": "Republic of Macedonia (FYROM)", "cn": "馬其頓"},  
    {"code": "ML", "en": "Mali", "cn": "馬裡"},  
    {"code": "MM", "en": "Myanmar (Burma)", "cn": "緬甸"},  
    {"code": "MN", "en": "Mongolia", "cn": "蒙古國"},  
    {"code": "MP", "en": "Northern Mariana Islands", "cn": "北馬裡亞納群島"},  
    {"code": "MQ", "en": "Martinique", "cn": "馬提尼克"},  
    {"code": "MR", "en": "Mauritania", "cn": "茅利塔尼亞"},  
    {"code": "MS", "en": "Montserrat", "cn": "蒙塞拉特島"},  
    {"code": "MT", "en": "Malta", "cn": "馬耳他"},  
    {"code": "MU", "en": "Mauritius", "cn": "模里西斯"},  
    {"code": "MV", "en": "Maldives", "cn": "馬爾地夫"},  
    {"code": "MW", "en": "Malawi", "cn": "馬拉維"},  
    {"code": "MX", "en": "Mexico", "cn": "墨西哥"},  
    {"code": "MY", "en": "Malaysia", "cn": "馬來西亞"},  
    {"code": "MZ", "en": "Mozambique", "cn": "莫三比克"},  
    {"code": "NA", "en": "Namibia", "cn": "納米比亞"},  
    {"code": "NC", "en": "New Caledonia", "cn": "新喀里多尼亞"},  
    {"code": "NE", "en": "Niger", "cn": "尼日"},  
    {"code": "NF", "en": "Norfolk Island", "cn": "諾福克島"},  
    {"code": "NG", "en": "Nigeria", "cn": "奈及利亞"},  
    {"code": "NI", "en": "Nicaragua", "cn": "尼加拉瓜"},  
    {"code": "NL", "en": "Netherlands", "cn": "荷蘭"},  
    {"code": "NO", "en": "Norway", "cn": "挪威"},  
    {"code": "NP", "en": "Nepal", "cn": "尼泊爾"},  
    {"code": "NR", "en": "Nauru", "cn": "諾魯"},  
    {"code": "NU", "en": "Niue", "cn": "紐埃"},  
    {"code": "NZ", "en": "New Zealand", "cn": "紐西蘭"},  
    {"code": "OM", "en": "Oman", "cn": "阿曼"},  
    {"code": "PA", "en": "Panama", "cn": "巴拿馬"},  
    {"code": "PE", "en": "Peru", "cn": "祕魯"},  
    {"code": "PF", "en": "French polynesia", "cn": "法屬波利尼西亞"},  
    {"code": "PG", "en": "Papua New Guinea", "cn": "巴布亞紐幾內亞"},  
    {"code": "PH", "en": "The Philippines", "cn": "菲律賓"},  
    {"code": "PK", "en": "Pakistan", "cn": "巴基斯坦"},  
    {"code": "PL", "en": "Poland", "cn": "波蘭"},  
    {"code": "PM", "en": "Saint-Pierre and Miquelon", "cn": "聖皮埃爾和密克隆"},  
    {"code": "PN", "en": "Pitcairn Islands", "cn": "皮特凱恩群島"},  
    {"code": "PR", "en": "Puerto Rico", "cn": "波多黎各"},  
    {"code": "PS", "en": "Palestinian territories", "cn": "巴勒斯坦"},  
    {"code": "PT", "en": "Portugal", "cn": "葡萄牙"},  
    {"code": "PW", "en": "Palau", "cn": "帛琉"},  
    {"code": "PY", "en": "Paraguay", "cn": "巴拉圭"},  
    {"code": "QA", "en": "Qatar", "cn": "卡達"},  
    {"code": "RE", "en": "Réunion", "cn": "留尼汪"},  
    {"code": "RO", "en": "Romania", "cn": "羅馬尼亞"},  
    {"code": "RS", "en": "Serbia", "cn": "塞爾維亞"},  
    {"code": "RU", "en": "Russian Federation", "cn": "俄羅斯"},  
    {"code": "RW", "en": "Rwanda", "cn": "盧安達"},  
    {"code": "SA", "en": "Saudi Arabia", "cn": "沙烏地阿拉伯"},  
    {"code": "SB", "en": "Solomon Islands", "cn": "索羅門群島"},  
    {"code": "SC", "en": "Seychelles", "cn": "塞席爾"},  
    {"code": "SD", "en": "Sudan", "cn": "蘇丹"},  
    {"code": "SE", "en": "Sweden", "cn": "瑞典"},  
    {"code": "SG", "en": "Singapore", "cn": "新加坡"},  
    {"code": "SH", "en": "St. Helena & Dependencies", "cn": "聖赫勒拿"},  
    {"code": "SI", "en": "Slovenia", "cn": "斯洛維尼亞"},  
    {"code": "SJ", "en": "Svalbard and Jan Mayen", "cn": "斯瓦爾巴群島和揚馬延島"},  
    {"code": "SK", "en": "Slovakia", "cn": "斯洛伐克"},  
    {"code": "SL", "en": "Sierra Leone", "cn": "獅子山"},  
    {"code": "SM", "en": "San Marino", "cn": "聖馬利諾"},  
    {"code": "SN", "en": "Senegal", "cn": "塞內加爾"},  
    {"code": "SO", "en": "Somalia", "cn": "索馬利亞"},  
    {"code": "SR", "en": "Suriname", "cn": "蘇利南"},  
    {"code": "SS", "en": "South Sudan", "cn": "南蘇丹"},  
    {"code": "ST", "en": "Sao Tome & Principe", "cn": "聖多美和普林西比"},  
    {"code": "SV", "en": "El Salvador", "cn": "薩爾瓦多"},  
    {"code": "SX", "en": "Sint Maarten", "cn": "荷屬聖馬丁"},  
    {"code": "SY", "en": "Syria", "cn": "敘利亞"},  
    {"code": "SZ", "en": "Swaziland", "cn": "史瓦濟蘭"},  
    {"code": "TC", "en": "Turks & Caicos Islands", "cn": "特克斯和凱科斯群島"},  
    {"code": "TD", "en": "Chad", "cn": "查德"},  
    {"code": "TF", "en": "French Southern Territories", "cn": "法屬南部領地"},  
    {"code": "TG", "en": "Togo", "cn": "多哥"},  
    {"code": "TH", "en": "Thailand", "cn": "泰國"},  
    {"code": "TJ", "en": "Tajikistan", "cn": "塔吉克"},  
    {"code": "TK", "en": "Tokelau", "cn": "托克勞"},  
    {"code": "TL", "en": "Timor-Leste (East Timor)", "cn": "東帝汶"},  
    {"code": "TM", "en": "Turkmenistan", "cn": "土庫曼"},  
    {"code": "TN", "en": "Tunisia", "cn": "突尼西亞"},  
    {"code": "TO", "en": "Tonga", "cn": "湯加"},  
    {"code": "TR", "en": "Turkey", "cn": "土耳其"},  
    {"code": "TT", "en": "Trinidad & Tobago", "cn": "千里達及托巴哥"},  
    {"code": "TV", "en": "Tuvalu", "cn": "吐瓦魯"},  
    {"code": "TZ", "en": "Tanzania", "cn": "坦尚尼亞"},  
    {"code": "UA", "en": "Ukraine", "cn": "烏克蘭"},  
    {"code": "UG", "en": "Uganda", "cn": "烏干達"},  
    {"code": "UM", "en": "United States Minor Outlying Islands", "cn": "美國本土外小島嶼"},  
    {"code": "UY", "en": "Uruguay", "cn": "烏拉圭"},  
    {"code": "UZ", "en": "Uzbekistan", "cn": "烏茲別克"},  
    {"code": "VA", "en": "Vatican City (The Holy See)", "cn": "梵蒂岡"},  
    {"code": "VC", "en": "St. Vincent & the Grenadines", "cn": "聖文森及格瑞那丁"},  
    {"code": "VE", "en": "Venezuela", "cn": "委內瑞拉"},  
    {"code": "VG", "en": "British Virgin Islands", "cn": "英屬維爾京群島"},  
    {"code": "VI", "en": "United States Virgin Islands", "cn": "美屬維爾京群島"},  
    {"code": "VN", "en": "Vietnam", "cn": "越南"},  
    {"code": "VU", "en": "Vanuatu", "cn": "萬那杜"},  
    {"code": "WF", "en": "Wallis and Futuna", "cn": "瓦利斯和富圖納"},  
    {"code": "WS", "en": "Samoa", "cn": "薩摩亞"},  
    {"code": "YE", "en": "Yemen", "cn": "葉門"},  
    {"code": "YT", "en": "Mayotte", "cn": "馬約特"},  
    {"code": "ZA", "en": "South Africa", "cn": "南非"},  
    {"code": "ZM", "en": "Zambia", "cn": "尚比亞"},  
    {"code": "ZW", "en": "Zimbabwe", "cn": "辛巴威"}  
]

export const City = [
    {"name":"基隆市"},
    {"name":"台北市"},
    {"name":"新北市"},
    {"name":"桃園縣"},
    {"name":"新竹市"},
    {"name":"新竹縣"},
    {"name":"苗栗縣"},
    {"name":"台中市"},
    {"name":"彰化縣"},
    {"name":"南投縣"},
    {"name":"雲林縣"},
    {"name":"嘉義市"},
    {"name":"台南市"},
    {"name":"高雄市"},
    {"name":"屏東縣"},
    {"name":"台東縣"},
    {"name":"花蓮縣"},
    {"name":"宜蘭縣"},
    {"name":"澎湖縣"},
    {"name":"金門縣"},
    {"name":"連江縣"}
]
